### ISSUE TITLE
firetable@1.5.0: The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by zakblacki** [FiretableProject/firetable-cli#3]
Can't install this with node 14.17.3 not compatible

> warning firetable > firebase-tools > request > har-validator@5.1.5: this library is no longer supported
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
error firetable@1.5.0: The engine "node" is incompatible with this module. Expected version ">=10 <13". Got "14.17.3"
error Found incompatible module.

**Comment by notsidney** [comment]
Hi, we’ve removed this Node requirement in v1.5.1
